### ISSUE TITLE
mainType is missing some types

### ISSUE THREAD

**Issue by transitive-bullshit** [Zoha/movier#164]
Hey @Zoha, this library is excellent — thanks so much 💯

Found a few issues while using `movier` for a pet project.

For the `mainType` field, currently only `movie`, `series`, and `seriesEpisode` are supported. However, IMDB supports several more types that you can infer by looking at the [titles.basics interface](https://www.imdb.com/interfaces/).

These include:
- `video` (seems to be mostly animated movies)
- `tvSpecial`
- `tvMovie`
- `short`

All of these are easy to differentiate in the HTML except for `short`, which the only indication is that `short` is included in the list of title `genres`. `short` is currently filtered out of the output `genres`, however, so there is no guaranteed way to figure this out with the current output.

Since `mainType` is such an important field for understanding IMDB's data model, this is imho pretty important. Happy to provide a PR to fix.

**Comment by Zoha** [comment]
It's correct @transitive-bullshit first I wanted to include all these types but, then I think I decided to use just these three types 
and in the future add a subtype to include these other types, for example, I see short as a movie, and it's more like a category of it
it would be great if you can contribute to these, and we can add these to the next version (  v2.2 ) 👍

**Comment by transitive-bullshit** [comment]
> It's correct @transitive-bullshit first I wanted to include all these types but, then I think I decided to use just these three types and in the future add a subtype to include these other types, for example, I see short as a movie, and it's more like a category of it.

Honestly, I'd much prefer to stay as close as possible to IMDB's official schemas and data formatting decisions. That will make it easier as things change in the future. If developers want to introduce their own abstractions / derived types outside of the "official" IMDB ones, then that is fine, but it's much easier to maintain software like this imho if you stick to the underlying platform's existing conventions as much as possible.

This is what I've done, for instance, with https://github.com/NotionX/react-notion-x, and it's worked out really well.

Happy to submit a PR.

**Comment by Zoha** [comment]
It makes sence @transitive-bullshit 
so plz submit a pr for it if you can 
thanks 😊
