### ISSUE TITLE
getTitleDetailsByIMDBId makes 12 calls to IMDB; would be nice to have a "lite" option

### ISSUE THREAD

**Issue by transitive-bullshit** [Zoha/movier#165]
Currently, the main title resolver `IMDBTitleDetailsResolver` makes 12 HTTP GET calls to IMDB per title. For my use case (and I'm sure many others), many of these details are excessive, and if you're being careful w.r.t. rate-limiting, these 12x HTTP calls start to become a real problem.

```ts
      this.getMainPageHTMLData(),
      this.getReleaseInfoPageHTMLData(),
      // this.getFullCreditsPageHTMLData(),
      this.getRatingsPageHTMLData(),
      // this.getCompanyCreditsPageHTMLData(),
      // this.getTaglinesPageHTMLData(),
      // this.getPosterImagesFirstPageHTMLData(),
      // this.getStillFrameImagesFirstPageHTMLData(),
      // this.getAwardsPageHTMLData(),
      this.getCriticReviewsHTMLData(),
      // this.getQuotesPageHTMLData(),
      // this.getGoofsPageHTMLData(),
```

I've tweaked my local version of `movier` to only retrieve a `lite` version of the title with 4 HTTP GET requests per title and instead return a `Partial<ITitle>`.

I'm guessing others may find this type of functionality useful as well, so thought I'd share the idea. Happy to submit a PR if desired.

Cheers.

**Comment by Zoha** [comment]
That seems a good Idea @transitive-bullshit , it's great if you can contribute
I think we can have an include option and load the data ( and request to pages ) based on that 
what do you think?

**Comment by transitive-bullshit** [comment]
I was thinking of two options:

1. We just have a `lite` option which implicitly only loads a subset of the data.
2. We allow the user to `select` which fields they want in the return object and infer which HTTP requests need to be fetched based on this. This is similar to how databases allow you to select which fields to return for queries.

Option #1 is simpler. Option #2 is more customizable.

Thoughts?

**Comment by Zoha** [comment]
I prefer #2
By doing so we would get only the pages that are needed
The only challenge is the way that user sends the options because we should keep it simple as possible ( with minimum arguments )
Maybe we can have an exclude option instead of include
