### ISSUE TITLE
Dates object is empty 

### ISSUE THREAD

**Issue by drhuseyinunal** [Zoha/movier#239]
Hi bro, thank you so much. This is an awesome module. But I have an issue, the dates object is empty. I cannot take any data about start and end dates of movies… could you fix it please…?

**Comment by Zoha** [comment]
Hi @drhuseyinunal 
Please give me more information . what is the path to the date object ? for example `allReleaseDates[0].date`
and for which title/person you are getting the result? please send the id for debug

**Comment by drhuseyinunal** [comment]
movie: https://www.imdb.com/title/tt0816692/

**// 1. titleYear is 0**
{
...
'Interstellar',
worldWideName: 'Interstellar',
otherNames: [],
titleYear: 0,
genres: [ 'adventure', 'drama', 'sciFi' ],
...
}

**// 2. allReleaseDates is [] and dates is like this:**
{
...
allReleaseDates: [],
dates: {
   startCountry: '',
   startDate: '',
   startExtraInfo: '',
   startYear: 0,
   titleYear: 0,
   isEnded: false
   },
...
}

_all other outputs are working perfectly. but those outputs are have issues._

**Comment by aloima** [comment]
I found a way for getting release dates but there is a problem, you can get only first five release dates because of design system of IMDb. We can't click more (or all) button without a browser automation library.
![image](https://user-images.githubusercontent.com/83824840/216763436-0722c43b-78ee-4ef2-99cd-36fe6d56ab0d.png)

If the maintainer approves this, I can open a pull request after complete getting title year.

**Comment by drhuseyinunal** [comment]
are you there? @Zoha

**Comment by Zoha** [comment]
there is some updates in IMDB website 
currently I'm working on new major version 
that would fix the issue + will be more stable 
would be ready in this week @drhuseyinunal

**Comment by drhuseyinunal** [comment]
okay, thank you so much. i'm waiting the stable version. take care @Zoha

**Comment by daomengRen** [comment]
thank you so much. i'm also waiting the stable version.

**Comment by drhuseyinunal** [comment]
@Zoha

**Comment by Zoha** [comment]
sorry for the late 
it would be ready in the next 2 days

**Comment by drhuseyinunal** [comment]
np bro still waiting for the update

**Comment by Zoha** [comment]
v3 released 
https://github.com/Zoha/movier/releases/tag/v3.0.0
@drhuseyinunal  @daomengRen

**Comment by drhuseyinunal** [comment]
didn't fixed. control the result again please. your dates object is not correct.

**Comment by Zoha** [comment]
as you mentioned in other issue, this is fixed in v3.0.1 @drhuseyinunal
